# Generated by Django 4.0.1 on 2023-03-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(default='IN', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='987456321', max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
